name: Feature Request
description: Suggest a new feature for the Themes plugin
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: dropdown
    id: willing
    attributes:
      label: Would you submit a PR?
      options:
        - "Yes"
        - "Yes, with guidance"
        - "No"
    validations:
      required: true
